### ISSUE TITLE
Der Pott

### ISSUE THREAD

**Issue by perprogramming** [perprogramming/bonnliga-website#4]
Was ist im Pott (und zwar aufgeschlüsselt nach Ladies, Pro, Amateur, Masterturnier...)

**Comment by ErrorProne** [comment]
Der komplette Pott muss noch irgendwo berechnet werden (+ Sponsorgrundwert).

Könnte durchaus bei jedem Seitenaufruf gemacht (Count auf Turniere gejoined mit den Teilnehmern / 2 + Sponsorengelder) oder aber einmal bei einer Turniereintragung berechnet werden.

**Comment by perprogramming** [comment]
Thanks!
