### ISSUE TITLE
Gleicher Rang in der Rangliste bei gleicher Punktzahl

### ISSUE THREAD

**Issue by perprogramming** [perprogramming/bonnliga-website#44]
Wollen wir, dass wenn zwei Leute die gleiche Punktzahl haben, dass diese dann auch den gleichen Rang haben? Momentan ist es nicht so, bei gleicher Punktzahl hat der im Alphabet vorne stehende (Vorname + Nachname) gewonnen.

**Comment by ErrorProne** [comment]
wir wollen!
