### ISSUE TITLE
Das Layout der Sponsorenseite ist kaputt

### ISSUE THREAD

**Issue by perprogramming** [perprogramming/bonnliga-website#47]

**Comment by ErrorProne** [comment]
ist es?

**Comment by perprogramming** [comment]
Also ich habe da immer einen horizontalen Scrollbalken, weil der gestrichelte Kasten nach rechts rausragt...

**Comment by ErrorProne** [comment]
welcher browser, welche version? mein chrome zeigt alles wundervoll an

edit: ich zieh alles zurück. ich bin lediglich vollkommen blind. fix ich gleich
