### ISSUE TITLE
Das Layout bei Facts ist kaputt

### ISSUE THREAD

**Issue by perprogramming** [perprogramming/bonnliga-website#49]
Man sieht es unten am Copyright (klebt links am Rand). Das lag bisher immer daran, dass irgendwo ein div nicht geschlossen wurde...

**Comment by perprogramming** [comment]
@ErrorProne: Ich fixe es auch gerne, komme aber erst heute nacht wieder dazu..

**Comment by ErrorProne** [comment]
gar nicht gesehen. prüf ich gleich
